### ISSUE TITLE
Duplication of code

### ISSUE THREAD

**Issue by Altai-man** [retupmoca/P6-Compress-Zlib#10]
Methods `inflate` and `deflate` in the stream class are almost identical, except for a call to underlying library and initial flags. Will it be good to get rid of the duplication(by method extraction or conditional execution)? I can send a PR with this changes, but I'm not confident about purpose of the duplication(is it a quick hack or some hidden aim). I'll write a patch if it can be merged.

**Comment by retupmoca** [comment]
The duplication is mostly accidental in this case - mostly because I was learning how the zlib libraries worked at the time I wrote this.

If you write a patch to remove the duplication, I will gladly merge it!

**Comment by Altai-man** [comment]
PR is waiting.
