### ISSUE TITLE
uncompress() for gzip buffer gives an error

### ISSUE THREAD

**Issue by hstejas** [retupmoca/P6-Compress-Zlib#20]
uncompress data error
  in sub _internal-compression at /home/user/rakudo/install/share/perl6/site/sources/193507957FCEB8E7040AA77BFA23FE450F913747 (Compress::Zlib) line 26
  in sub uncompress at /home/user/rakudo/install/share/perl6/site/sources/193507957FCEB8E7040AA77BFA23FE450F913747 (Compress::Zlib) line 43

$  perl6 -v
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by pmqs** [comment]
@hstejas - Can you post some self-contained code that triggers the issue?

**Comment by hstejas** [comment]
Example:
```
      use Compress::Zlib; 
      # gzipped buffer that contains "1234"
      my Buf $buf = Buf.new(
      0x1f, 0x8b, 0x08, 0x08, 0x9f, 0xfa, 0xf8, 0x5c, 0x00, 0x03, 0x73, 0x6d,
      0x61, 0x6c, 0x6c, 0x2e, 0x74, 0x78, 0x74, 0x00, 0x33, 0x34, 0x32, 0x36,
      0xe1, 0x02, 0x00, 0x21, 0x17, 0x93, 0x7d, 0x05, 0x00, 0x00, 0x00);
      uncompress($buf);
```

**Comment by pmqs** [comment]
I saved your compressed data to disk and checked what format it is in. 

```
$ file /tmp/d
/tmp/d: gzip compressed data, was "small.txt", from Unix, last modified: Thu Jun  6 12:35:59 2019
```
The `uncompress` function expects **zlib** compressed data. You are giving it **gzip** compressed data.

**Comment by hstejas** [comment]
OK, that wasn't really clear from the examples. But I think a similar function for gzip will be good to have.
